apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadjrjv9216-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadjrjv9216-tenant-component
    app.kubernetes.io/part-of: loadjrjv9216-tenant-app
  name: loadjrjv9216-tenant-component
  namespace: loadjrjv9216-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadjrjv9216-tenant-component
    weight: null
status: {}
